version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  # Ensure the desired Java version is set
    commands:
      - echo "Installing Maven dependencies..."
      - mvn clean install -DskipTests

  pre_build:
    commands:
      - echo "Setting up Chrome and ChromeDriver on Amazon Linux..."

      # Install Google Chrome
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - yum install -y ./google-chrome-stable_current_x86_64.rpm
      - google-chrome --version  # Verify Chrome installation

      # Install ChromeDriver
      - wget -N https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip
      - mv chromedriver /usr/bin/chromedriver
      - chmod +x /usr/bin/chromedriver
      - chromedriver --version  # Verify ChromeDriver installation

  build:
    commands:
      - echo "Running Serenity Screenplay tests..."
      - mvn clean verify

  post_build:
    commands:
      - echo "Build completed successfully!"
      - echo "Archiving Serenity test reports..."

artifacts:
  files:
    - target/site/serenity/**/*
    - target/serenity-summary.html
    - "**/*.xml"
  discard-paths: no
